spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create

  datasource:
    url: ${jdbc.url}
    username: ${jdbc.user}
    password: ${jdbc.password}
    driver-class-name: ${jdbc.driver}
